### ISSUE TITLE
XP-arkiv TODO

### ISSUE THREAD

**Issue by anders-nom** [navikt/navno-cms-archive#39]
MVP:
- [x] Layers selector i frontend
- [x] Støtte layers i contentTree XP service
- [x] #44
- [x] Implementere nedlasting av filer i frontend
- [x] Sette opp service for nedlasting av filer
- [x] #48
- [x] Håndtere versjoner med ulik contentId (pga historikk før layers-migrering)
- [x] Sørge for at avpublisert innhold også kan hentes ut fra XP (alt innhold som på ett eller annet tidspunkt har vært publisert bør kunne vises)
- [x] Legge til "latest" i versjonsvelgeren
- [x] Inkludere innhold fra XP-arkivet
- [x] Indikere lokaliserings-state i frontend content navigering
- [x] Hindre redirects fra XP-frontend
- [x] #58

SoonTM:
- [x] #51
- [x] Vi må filtrere bort versjoner som kun har vært utkast
- [x] #59
- [x] #60
- [x] #80
- [x] #76
- [x] Felles PDF-tjeneste https://github.com/navikt/navno-cms-archive/issues/23
- [x] Funksjonalitet for søk https://github.com/navikt/navno-cms-archive/issues/26
- [x] #77
